name: ${APP_NAME}
configs:
  Devel Run: debug
  Devel Archive: release
  Prod Run: debug
  Prod Archive: release
settings:
  configs:
    Devel Run:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVEL DEBUG
    Devel Archive:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVEL
    Prod Run:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD DEBUG
    Prod Archive:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD
options:
  bundleIdPrefix: it.synesthesia
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "12.0"
fileGroups:
- project.yml
- Configuration
- Makefile
targets:
  ${APP_NAME}:
    type: application
    platform: iOS
    sources: "Sources/App"
    preBuildScripts:
      - name: "SwiftLint"
        script: |
                swiftlint --config "${SRCROOT}/.swiftlint.yml"
    dependencies:
    - target: Core
    settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_IDENTIFIER}
  Core:
    type: framework
    platform: iOS
    sources: "Sources/Core"
    settings:
        base:
            PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_IDENTIFIER}.framework
